apiVersion: v1
kind: Pod
metadata:
  name: simple
  namespace: default
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80