version: '3.7'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - 'gitlab-runner:/etc/gitlab-runner'

volumes:
  gitlab-runner:
    labels:
      - "description= company gitlab runner"
