version: '3.7'

services:
  zoo:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo
    container_name: zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo:2888:3888
      ZOOKEEPER_SASL_ENABLED: "true"
      ZOOKEEPER_ALLOW_ANONYMOUS_LOGINS: "false"
      ZOOKEEPER_AUTH_PROVIDER_1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      ZOOKEEPER_SERVER_JVMFLAGS: >
        -Djava.security.auth.login.config=/etc/zookeeper.jaas
        -Dzookeeper.allowSaslFailedClients=false
    volumes:
      - ./conf/zookeeper.jaas:/etc/zookeeper.jaas
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_LISTENERS: SASL_PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      
      # SASL Configuration
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka.jaas -Dzookeeper.sasl.client=true -Dzookeeper.sasl.client.username=kafka -Dzookeeper.sasl.clientconfig=Client"
      
      # Zookeeper SASL
      KAFKA_ZOOKEEPER_SASL_ENABLED: "true"
      KAFKA_ZOOKEEPER_SASL_MECHANISM: DIGEST-MD5
    volumes:
      - /Users/miladsorour/Documents/devops/conf/kafka.jaas:/etc/kafka.jaas
      - kafka-data:/var/lib/kafka/data
    depends_on:
      - zoo

volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-data: