services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    platform: linux/amd64
    restart: always
    environment:
      - ORACLE_PASSWORD=root
    ports:
      - 1521:1521
    volumes:
      - /Users/milad/IdeaProjects.nosync/docker-volume:/opt/oracle/oradata
