version: '2'

services:
  oracle:
    image: gvenzl/oracle-xe:18-slim
    restart: always
    environment:
      - ORACLE_PASSWORD=root
    ports:
      - 1521:1521
    volumes:
      - /Users/miladsorour/Documents/devOps/docker/oraclenew:/opt/oracle/oradata

