services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
      - redis-data-conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=1234
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  redis-data: {}
  redis-data-conf: {}