apiVersion: v1
kind: Namespace
metadata:
  name: share-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-generator-pvc
  namespace: share-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  namespace: share-pvc
spec:
  containers:
    - name: log-generator
      image: busybox
      command: ["sh", "-c", "while true; do echo 'App Log' >> /logs/app.log; sleep 5; done"]
      volumeMounts:
        - name: log-generator-data
          mountPath: /logs
  volumes:
    - name: log-generator-data
      persistentVolumeClaim:
        claimName: log-generator-pvc
  nodeSelector:
    size: small
---
apiVersion: v1
kind: Pod
metadata:
  name: filebeat-ish
  namespace: share-pvc
spec:
  containers:
    - name: filebeat-ish
      image: busybox
      command: ["sh", "-c", "while true; do cd /logs/; ls ; sleep 5; done"]
      volumeMounts:
        - name: filebeat-ish-data
          mountPath: /logs
  volumes:
    - name: filebeat-ish-data
      persistentVolumeClaim:
        claimName: log-generator-pvc
  nodeSelector:
    size: small