---
- hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Download and execute Docker installation script
      shell: curl -fsSL https://get.docker.com | sh

    - name: Start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add current login user to Docker group
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes
